id: A76D1514D
title: Prayer to Kongtrul Yönten Gyatso
type: translation
pechas:
- IB969555D
- I78C4EFF8
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:02:10.461138
  last_modified_at: 2023-01-04 12:02:10.461143
  collections:
  - Jamgön Kongtrul Lodrö Thaye Series
  - Works of Tibetan Masters
alignment_to_base:
  IB969555D/1410: CE69
  I78C4EFF8/A438: CE69
